Check for docker, add bash completion, replace vi with vim

diff --git a/cloudenv b/cloudenv
--- a/cloudenv
+++ b/cloudenv
@@ -18,22 +18,37 @@ if [ ! -d $home_directory ]; then
   exit 1
 fi
 
-if [ ! "$(docker ps -q -f name=$container_name)" ]; then
+if hash docker 2>/dev/null; then
 
-  if [ "$(docker ps -aq -f status=exited -f name=$container_name)" ]; then
-    docker rm -f $container_name
-    echo $?
+  if [ ! "$(docker ps -q -f name=$container_name)" ]; then
+
+    if [ "$(docker ps -aq -f status=exited -f name=$container_name)" ]; then
+      docker rm -f $container_name
+    fi
+
+    docker pull $image_name:$image_tag
+
+    if hash id 2>/dev/null; then
+      docker run -dit --name $container_name --hostname $container_name -w="$HOME" --mount type=bind,source=$home_directory,target="$HOME" -e TZ=$timezone -e HOST_USER_NAME="$(id -u -n)" -e HOST_GROUP_NAME="$(id -g -n)" -e HOST_USER_ID="$(id -u)" -e HOST_GROUP_ID="$(id -g)" -e HOST_HOME_DIRECTORY="$HOME" $image_name:$image_tag &> /dev/null
+      retVal=$?
+      if [ $retVal -ne 0 ]; then
+        echo "Error starting cloudenv container!"
+        exit 1
+      fi
+      docker exec -it $container_name su-exec "$(id -u)":"$(id -g)" $user_shell
+    else
+      docker run -dit --name $container_name --hostname $container_name -w="/home/user" --mount type=bind,source=$home_directory,target="/home/user" -e TZ=$timezone $image_name:$image_tag &> /dev/null
+      retVal=$?
+      if [ $retVal -ne 0 ]; then
+        echo "Error starting cloudenv container!"
+        exit 1
+      fi
+      docker exec -it $container_name su-exec 1000:1000 $user_shell
+    fi
   fi
 
-  docker pull $image_name:$image_tag
+  docker rm -f $container_name &> /dev/null
 
-  if hash id 2>/dev/null; then
-    docker run -dit --name $container_name --hostname $container_name -w="$HOME" --mount type=bind,source=$home_directory,target="$HOME" -e TZ=$timezone -e HOST_USER_NAME="$(id -u -n)" -e HOST_GROUP_NAME="$(id -g -n)" -e HOST_USER_ID="$(id -u)" -e HOST_GROUP_ID="$(id -g)" -e HOST_HOME_DIRECTORY="$HOME" $image_name:$image_tag &> /dev/null
-    docker exec -it $container_name su-exec "$(id -u)":"$(id -g)" $user_shell
-  else
-    docker run -dit --name $container_name --hostname $container_name -w="/home/user" --mount type=bind,source=$home_directory,target="/home/user" -e TZ=$timezone $image_name:$image_tag &> /dev/null
-    docker exec -it $container_name su-exec 1000:1000 $user_shell
-  fi
+else
+  echo "docker command not found, you must install docker first."
 fi
-
-docker rm -f $container_name &> /dev/null
