Add SSH auth-socket passthrough

diff --git a/cloudenv b/cloudenv
--- a/cloudenv
+++ b/cloudenv
@@ -18,6 +18,11 @@ if [ ! -d $home_directory ]; then
   exit 1
 fi
 
+if [ -z "${SSH_AGENT_PID:-}" ] || [ -z "${SSH_AUTH_SOCK:-}" ]; then
+  echo '$SSH_AGENT_PID or $SSH_AUTH_SOCK are empty, unable to use host SSH agent.'
+  declare -r SSH_AGENT_PID='0'
+fi
+
 if hash docker 2>/dev/null; then
 
   if [ ! "$(docker ps -q -f name=$container_name)" ]; then
@@ -26,19 +31,74 @@ if hash docker 2>/dev/null; then
       docker rm -f $container_name
     fi
 
+    # Always pull latest image
     docker pull $image_name:$image_tag
 
     if hash id 2>/dev/null; then
-      docker run -dit --name $container_name --hostname $container_name -w="$HOME" --mount type=bind,source=$home_directory,target="$HOME" -e TZ=$timezone -e HOST_USER_NAME="$(id -u -n)" -e HOST_GROUP_NAME="$(id -g -n)" -e HOST_USER_ID="$(id -u)" -e HOST_GROUP_ID="$(id -g)" -e HOST_HOME_DIRECTORY="$HOME" $image_name:$image_tag &> /dev/null
-      retVal=$?
+
+      if [ "${SSH_AGENT_PID}" -eq 0 ]; then
+        # Run without ssh agent passthrough
+        docker run -dit \
+          --name $container_name \
+          --hostname $container_name \
+          -w="$HOME" \
+          --mount type=bind,source=$home_directory,target="$HOME" \
+          --mount type=bind,source="`dirname $SSH_AUTH_SOCK`",target="`dirname $SSH_AUTH_SOCK`" \
+          -e TZ=$timezone -e HOST_USER_NAME="$(id -u -n)" \
+          -e HOST_GROUP_NAME="$(id -g -n)" \
+          -e HOST_USER_ID="$(id -u)" \
+          -e HOST_GROUP_ID="$(id -g)" \
+          -e HOST_HOME_DIRECTORY="$HOME" \
+          $image_name:$image_tag &> /dev/null
+        retVal=$?
+      else
+        # Run with ssh agent passthrough, full options, and all bind-mounts
+        docker run -dit \
+          --name $container_name \
+          --hostname $container_name \
+          -w="$HOME" \
+          --mount type=bind,source=$home_directory,target="$HOME" \
+          --mount type=bind,source="`dirname $SSH_AUTH_SOCK`",target="`dirname $SSH_AUTH_SOCK`" \
+          -e TZ=$timezone -e HOST_USER_NAME="$(id -u -n)" \
+          -e HOST_GROUP_NAME="$(id -g -n)" \
+          -e HOST_USER_ID="$(id -u)" \
+          -e HOST_GROUP_ID="$(id -g)" \
+          -e HOST_HOME_DIRECTORY="$HOME" \
+          -e SSH_AUTH_SOCK="${SSH_AUTH_SOCK}" \
+          $image_name:$image_tag &> /dev/null
+        retVal=$?
+      fi
       if [ $retVal -ne 0 ]; then
         echo "Error starting cloudenv container!"
         exit 1
       fi
       docker exec -it $container_name su-exec "$(id -u)":"$(id -g)" $user_shell
+
     else
-      docker run -dit --name $container_name --hostname $container_name -w="/home/user" --mount type=bind,source=$home_directory,target="/home/user" -e TZ=$timezone $image_name:$image_tag &> /dev/null
-      retVal=$?
+      if [ "${SSH_AGENT_PID}" -eq 0 ]; then
+        # Run without id or ssh agent passthrough
+        docker run -dit \
+          --name $container_name \
+          --hostname $container_name \
+          -w="/home/user" \
+          --mount type=bind,source=$home_directory,target="/home/user" \
+          --mount type=bind,source="`dirname $SSH_AUTH_SOCK`",target="`dirname $SSH_AUTH_SOCK`" \
+          -e TZ=$timezone \
+          $image_name:$image_tag &> /dev/null
+        retVal=$?
+      else
+        # Run without id, but with ssh agent passthrough
+        docker run -dit \
+          --name $container_name \
+          --hostname $container_name \
+          -w="/home/user" \
+          --mount type=bind,source=$home_directory,target="/home/user" \
+          --mount type=bind,source="`dirname $SSH_AUTH_SOCK`",target="`dirname $SSH_AUTH_SOCK`" \
+          -e TZ=$timezone \
+          -e SSH_AUTH_SOCK="${SSH_AUTH_SOCK}" \
+          $image_name:$image_tag &> /dev/null
+        retVal=$?
+      fi
       if [ $retVal -ne 0 ]; then
         echo "Error starting cloudenv container!"
         exit 1
